Add a soundness check to lint YAML files
swiftlang/github-workflows pull request #13
Opened 2024-10-03 23:33 UTC by ahoppen

2024-10-04 00:04 UTC, shahmishal commented
Next time, let’s try to separate formatting and feature work in separate PRs. This makes it easier to review the changes.

2024-10-04 00:18 UTC, ahoppen commented
https://github.com/swiftlang/github-workflows/pull/15 formats the files and https://github.com/swiftlang/github-workflows/pull/13 now depends on #15.

2024-10-04 16:25 UTC, ahoppen commented on .github/workflows/soundness.yml
> +      yamllint_container_image:
@shahmishal Would you like to have a separate option for the base image of `yamllint`, `spellcheck` and `flake8`? Or should all of this be one single options?

2024-10-09 08:05 UTC, FranzBusch requested changes

2024-10-09 08:05 UTC, FranzBusch commented on .github/workflows/soundness.yml
> +      image: ${{ inputs.yamllint_container_image }}
I don't think we need a container image at all here we can just run on the runner itself

2024-10-09 08:05 UTC, FranzBusch commented on .github/workflows/soundness.yml
> +          apt-get -qq update && apt-get -qq -y install yamllint
The runner itself comes with yamlint preinstalled so we don't have to install it here

2024-10-10 08:07 UTC, shahmishal approved these changes
LGTM!

2024-10-10 08:08 UTC, shahmishal commented
@FranzBusch, please feel free to merge it once you’ve reviewed it.

2024-10-10 10:05 UTC, FranzBusch approved these changes

2024-10-10 10:05 UTC, merged