Allow passing `--breakage-allowlist-path` to the API breakage check
swiftlang/github-workflows pull request #64
Opened 2024-11-14 20:52 UTC by ahoppen

2024-11-15 14:11 UTC, FranzBusch requested changes

2024-11-15 14:11 UTC, FranzBusch commented on .github/workflows/soundness.yml
> +      api_breakage_allowlist_path:
```suggestion
      api_breakage_check__allowlist_path:
```

2024-11-15 14:11 UTC, FranzBusch commented on .github/workflows/soundness.yml
> +            swift package diagnose-api-breaking-changes pull-base-ref --breakage-allowlist-path '${{ inputs.api_breakage_allowlist_path }}'
```suggestion
            swift package diagnose-api-breaking-changes pull-base-ref --breakage-allowlist-path '${{ inputs.api_breakage_check_allowlist_path }}'
```

2024-11-15 16:55 UTC, ahoppen commented on .github/workflows/soundness.yml
> +      api_breakage_allowlist_path:
Updated

2024-11-20 14:04 UTC, FranzBusch approved these changes

2024-11-20 14:04 UTC, merged